version: '3'
services:
  front:
    build:
      context: './client'
      dockerfile: Dockerfile
    ports:
      - 3000:80
    container_name: client-container
   
    depends_on:
      - backend
  backend:
    build:
      context: './api'
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    container_name: api-container
    env_file:
      - ./.env
    
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongo-container
   
    volumes:
      - mongoData:/data/db
    env_file:
      - ./.env
  nginx:
    build:
      context: './client/nginx'
    container_name: nginx
    hostname: nginx
    ports: 
      - 80:80
    depends_on:
      - backend
      - front
    


volumes:
  mongoData:



