version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - 3001:3001
    environment:
      
      MONGODB_URI: mongodb://0.0.0.0:27017
      DB_NAME: react-todo
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}